In [6]:
import pandas as pd

df=pd.read_csv('https://stats.idre.ucla.edu/stat/data/hsbdemo.csv')

In [7]:
display(df)

,id,female,ses,schtyp,prog,read,write,math,science,socst,honors,awards,cid
0,45,female,low,public,vocation,34,35,41,29,26,not enrolled,0,1
1,108,male,middle,public,general,34,33,41,36,36,not enrolled,0,1
2,15,male,high,public,vocation,39,39,44,26,42,not enrolled,0,1
3,67,male,low,public,vocation,37,37,42,33,32,not enrolled,0,1
4,153,male,middle,public,vocation,39,31,40,39,51,not enrolled,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,100,female,high,public,academic,63,65,71,69,71,enrolled,5,20
196,143,male,middle,public,vocation,63,63,75,72,66,enrolled,4,20
197,68,male,middle,public,academic,73,67,71,63,66,enrolled,7,20
198,57,female,middle,public,academic,71,65,72,66,56,enrolled,5,20
199,132,male,middle,public,academic,73,62,73,69,66,enrolled,3,20

In [8]:
import pandas as pd

def summarize_data(df, column_names, funs, group_by):
    # Dictionary to map function names to pandas aggregation functions
    agg_funcs = {
        "sum": "sum",
        "mean": "mean",
        "max": "max",
        "min": "min",
    }

    # Validate that all functions in funs are supported
    unsupported_funcs = [func for func in funs if func not in agg_funcs]
    if unsupported_funcs:
        raise ValueError(f"Unsupported functions: {unsupported_funcs}. Supported functions are: {list(agg_funcs.keys())}")

    # Define the aggregation dictionary
    aggregation = {}
    for col in column_names:
        for func in funs:
            aggregation[f"{col}_{func}"] = (col, agg_funcs[func])

    # Group by and aggregate
    result = (
        df.groupby(group_by)
        .agg(**aggregation)
        .reset_index()
    )

    return result

In [11]:
result=summarize_data(df,column_names=['read','write','math','science','socst'],funs=['sum','mean','max','min'],group_by='female')
print(result)

   female  read_sum  read_mean  read_max  read_min  write_sum  write_mean  \
0  female      5639  51.733945        76        28       5994   54.990826
1    male      4807  52.824176        76        31       4561   50.120879

   write_max  write_min  math_sum  ...  math_max  math_min  science_sum  \
0         67         35      5711  ...        72        33         5526
1         67         31      4818  ...        75        35         4844

   science_mean  science_max  science_min  socst_sum  socst_mean  socst_max  \
0     50.697248           69           29       5768   52.917431         71
1     53.230769           74           26       4713   51.791209         71

   socst_min
0         26
1         26

[2 rows x 21 columns]